### ISSUE TITLE
Allow Array only in path

### ISSUE THREAD

**Issue by ai** [polemius/storeon-localstorage#2]
If we will allow the only array in `path` we can dramatically reduce size. I think it will be a good compromise, most of your users will use array anyway.

**Comment by ai** [comment]
Also, we can rename argument `path` to `paths`

**Comment by polemius** [comment]
I have chaged the api to use only array of string. And also change the name of variable to `paths`. The size decrease to 185 B.

**Comment by ai** [comment]
Perfect
